/* ============================================================
   Customer behavior analysis - dbo.customer (3,900 rows)
   SQL Server / T-SQL
   ============================================================ */


--Q1. What is the total revenue generated by male vs. female customers?

SELECT
    gender,
    COUNT(*)                AS purchases,
    SUM(purchase_amount)    AS total_revenue,
    AVG(CAST(purchase_amount AS decimal(10,2))) AS avg_purchase,
    CAST(100.0 * SUM(purchase_amount)
         / SUM(SUM(purchase_amount)) OVER () AS decimal(5,2)) AS pct_of_revenue
FROM dbo.customer
GROUP BY gender
ORDER BY total_revenue DESC;


--Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT
    customer_id,
    age,
    gender,
    item_purchased,
    category,
    purchase_amount,
    discount_applied
FROM dbo.customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (SELECT AVG(CAST(purchase_amount AS decimal(10,2))) FROM dbo.customer)
ORDER BY purchase_amount DESC;


--Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5
    item_purchased,
    COUNT(*)                                 AS purchases,
    CAST(AVG(review_rating) AS decimal(4,2)) AS avg_review_rating
FROM dbo.customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT
    shipping_type,
    COUNT(*)                                            AS purchases,
    CAST(AVG(CAST(purchase_amount AS decimal(10,2))) AS decimal(6,2)) AS avg_purchase,
    SUM(purchase_amount)                                AS total_revenue
FROM dbo.customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY avg_purchase DESC;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue
--    between subscribers and non-subscribers.

SELECT
    subscription_status,
    COUNT(*)                                            AS purchases,
    CAST(AVG(CAST(purchase_amount AS decimal(10,2))) AS decimal(6,2)) AS avg_spend,
    SUM(purchase_amount)                                AS total_revenue,
    CAST(AVG(review_rating) AS decimal(4,2))            AS avg_review_rating
FROM dbo.customer
GROUP BY subscription_status
ORDER BY avg_spend DESC;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5
    item_purchased,
    COUNT(*)                                            AS total_purchases,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
    CAST(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
         / COUNT(*) AS decimal(5,2))                    AS pct_discounted
FROM dbo.customer
GROUP BY item_purchased
ORDER BY pct_discounted DESC;


--Q7. Segment customers into New, Returning, and Loyal based on their total number of
--    previous purchases, and show the count of each segment.
--    Thresholds: New <= 10, Returning 11-30, Loyal > 30 (previous_purchases runs 1-50).

WITH segmented AS (
    SELECT
        customer_id,
        previous_purchases,
        purchase_amount,
        CASE
            WHEN previous_purchases <= 10 THEN 'New'
            WHEN previous_purchases <= 30 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM dbo.customer
)
SELECT
    customer_segment,
    COUNT(*)                                            AS customer_count,
    CAST(100.0 * COUNT(*) / SUM(COUNT(*)) OVER () AS decimal(5,2)) AS pct_of_customers,
    CAST(AVG(CAST(purchase_amount AS decimal(10,2))) AS decimal(6,2)) AS avg_spend,
    SUM(purchase_amount)                                AS total_revenue
FROM segmented
GROUP BY customer_segment
ORDER BY
    CASE customer_segment WHEN 'New' THEN 1 WHEN 'Returning' THEN 2 ELSE 3 END;


--Q8. What are the top 3 most purchased products within each category?

WITH ranked AS (
    SELECT
        category,
        item_purchased,
        COUNT(*)             AS purchases,
        SUM(purchase_amount) AS total_revenue,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC, item_purchased) AS rn
    FROM dbo.customer
    GROUP BY category, item_purchased
)
SELECT
    category,
    item_purchased,
    purchases,
    total_revenue
FROM ranked
WHERE rn <= 3
ORDER BY category, purchases DESC;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely
--    to subscribe?

WITH buyers AS (
    SELECT
        CASE WHEN previous_purchases > 5 THEN 'Repeat buyer (>5)'
             ELSE 'Occasional buyer (<=5)' END AS buyer_type,
        subscription_status
    FROM dbo.customer
)
SELECT
    buyer_type,
    COUNT(*)                                            AS customers,
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribers,
    CAST(100.0 * SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END)
         / COUNT(*) AS decimal(5,2))                    AS pct_subscribed
FROM buyers
GROUP BY buyer_type
ORDER BY pct_subscribed DESC;


--Q10. What is the revenue contribution of each age group?

SELECT
    age_group,
    COUNT(*)                                            AS purchases,
    MIN(age)                                            AS youngest,
    MAX(age)                                            AS oldest,
    SUM(purchase_amount)                                AS total_revenue,
    CAST(AVG(CAST(purchase_amount AS decimal(10,2))) AS decimal(6,2)) AS avg_purchase,
    CAST(100.0 * SUM(purchase_amount)
         / SUM(SUM(purchase_amount)) OVER () AS decimal(5,2)) AS pct_of_revenue
FROM dbo.customer
GROUP BY age_group
ORDER BY total_revenue DESC;
